CREATE TABLE IF NOT EXISTS users (
  id            CHAR(36) PRIMARY KEY,
  email         VARCHAR(191) NOT NULL UNIQUE,
  password_hash VARCHAR(255) NOT NULL,
  name          VARCHAR(100) NOT NULL,
  avatar_initials VARCHAR(4) NOT NULL,
  avatar_color  VARCHAR(30) DEFAULT 'blue',
  role          ENUM('superadmin', 'user') NOT NULL DEFAULT 'user',
  department    VARCHAR(60),
  job_title     VARCHAR(120),
  presence      ENUM('online', 'away', 'dnd', 'meeting', 'offline') NOT NULL DEFAULT 'offline',
  status_text   VARCHAR(120),
  last_seen_at  DATETIME,
  is_active     TINYINT(1) NOT NULL DEFAULT 1,
  created_at    DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at    DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX idx_email (email),
  INDEX idx_presence (presence),
  INDEX idx_active (is_active)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
